module
public import GravityScreening.UnorientedClockGravity

@[expose] public section

/-!
# Conditional bridge to surface-flux area kinematics

In connection formulations of gravity, the densitized triad determines the
oriented flux through a two-surface, and positive area is the magnitude of that
flux.  The physical input is explicit: `IsTangentialFrameResponse` asserts that
the classified two-channel response acts on the two tangential frame vectors.
Conditional on that carrier statement, the determinant and quartic area laws
below are exact.
-/

namespace GravityScreening

/-- One gauge-fixed component of the oriented surface flux generated by two
tangential frame vectors. -/
def triadSurfaceFlux2 (u v : Fin 2 → ℝ) : ℝ :=
  u 0 * v 1 - u 1 * v 0

/-- Positive local area carried by the oriented surface flux. -/
def triadSurfaceArea2 (u v : Fin 2 → ℝ) : ℝ :=
  |triadSurfaceFlux2 u v|

/-- The explicit carrier hypothesis: the response matrix acts on both
tangential frame vectors of the surface patch. -/
def IsTangentialFrameResponse
    (M : Matrix (Fin 2) (Fin 2) ℝ)
    (before₀ before₁ after₀ after₁ : Fin 2 → ℝ) : Prop :=
  after₀ = M.mulVec before₀ ∧ after₁ = M.mulVec before₁

/-- A scalar isolated-horizon-style boundary relation before and after a
curvature response.  `c` represents the fixed nonzero coefficient relating a
gauge-fixed triad-flux component to the corresponding connection-curvature
component. -/
def IsScalarHorizonBoundaryTransport
    (c : ℝ) (M : Matrix (Fin 2) (Fin 2) ℝ)
    (triadBefore triadAfter curvatureBefore curvatureAfter : Fin 2 → ℝ) : Prop :=
  curvatureBefore = c • triadBefore ∧
    curvatureAfter = c • triadAfter ∧
    curvatureAfter = M.mulVec curvatureBefore

/-- If curvature and triad flux obey the same nonzero scalar boundary relation
at both endpoints, a curvature response is forced to act identically on the
triad flux.  This is the finite local algebra behind “fluctuate in tandem.” -/
theorem scalarHorizonBoundary_transports_response
    (c : ℝ) (M : Matrix (Fin 2) (Fin 2) ℝ)
    (triadBefore triadAfter curvatureBefore curvatureAfter : Fin 2 → ℝ)
    (hc : c ≠ 0)
    (htransport : IsScalarHorizonBoundaryTransport c M
      triadBefore triadAfter curvatureBefore curvatureAfter) :
    triadAfter = M.mulVec triadBefore := by
  rcases htransport with ⟨hbefore, hafter, hresponse⟩
  rw [hbefore, hafter, Matrix.mulVec_smul] at hresponse
  ext i
  apply mul_left_cancel₀ hc
  exact congrFun hresponse i

/-- A linear response on the tangential frame multiplies oriented surface flux
by its determinant. -/
theorem triadSurfaceFlux2_mulVec
    (M : Matrix (Fin 2) (Fin 2) ℝ) (u v : Fin 2 → ℝ) :
    triadSurfaceFlux2 (M.mulVec u) (M.mulVec v) =
      Matrix.det M * triadSurfaceFlux2 u v := by
  simp [triadSurfaceFlux2, Matrix.mulVec, dotProduct, Fin.sum_univ_succ,
    Matrix.det_fin_two]
  ring

/-- Carrier-explicit version of the oriented flux determinant law. -/
theorem tangentialFrameResponse_flux_scale
    (M : Matrix (Fin 2) (Fin 2) ℝ)
    (before₀ before₁ after₀ after₁ : Fin 2 → ℝ)
    (hcarrier : IsTangentialFrameResponse
      M before₀ before₁ after₀ after₁) :
    triadSurfaceFlux2 after₀ after₁ =
      Matrix.det M * triadSurfaceFlux2 before₀ before₁ := by
  rw [hcarrier.1, hcarrier.2]
  exact triadSurfaceFlux2_mulVec M before₀ before₁

/-- If the response preserves orientation, positive surface area scales by the
same determinant. -/
theorem tangentialFrameResponse_area_scale
    (M : Matrix (Fin 2) (Fin 2) ℝ)
    (before₀ before₁ after₀ after₁ : Fin 2 → ℝ)
    (hcarrier : IsTangentialFrameResponse
      M before₀ before₁ after₀ after₁)
    (hdet : 0 ≤ Matrix.det M) :
    triadSurfaceArea2 after₀ after₁ =
      Matrix.det M * triadSurfaceArea2 before₀ before₁ := by
  unfold triadSurfaceArea2
  rw [tangentialFrameResponse_flux_scale M before₀ before₁ after₀ after₁
    hcarrier, abs_mul, abs_of_nonneg hdet]

/-- If the unoriented clock-classified response is carried by a horizon
tangential frame, its oriented triad flux is multiplied by the exact quartic
screening factor. -/
theorem unorientedClock_forces_triadFluxResponse
    (M : Matrix (Fin 2) (Fin 2) ℝ) (q : ℝ)
    (before₀ before₁ after₀ after₁ : Fin 2 → ℝ)
    (hq : q ≠ 0)
    (hexchange : IsChannelExchangeSymmetric M)
    (hmean : HasUnitDiagonalMean M)
    (hcore : HasUnorientedCoreWeight M q)
    (hcarrier : IsTangentialFrameResponse
      M before₀ before₁ after₀ after₁) :
    triadSurfaceFlux2 after₀ after₁ =
      ((2 * q - 1) / q ^ 2) * triadSurfaceFlux2 before₀ before₁ := by
  rw [tangentialFrameResponse_flux_scale M before₀ before₁ after₀ after₁
    hcarrier]
  rw [unorientedClockWeight_forces_quarticResponse
    M q hq hexchange hmean hcore]

/-- For `q>1`, the same conditional bridge scales positive surface area by the
quartic factor. -/
theorem unorientedClock_forces_triadAreaResponse
    (M : Matrix (Fin 2) (Fin 2) ℝ) (q : ℝ)
    (before₀ before₁ after₀ after₁ : Fin 2 → ℝ)
    (hq : 1 < q)
    (hexchange : IsChannelExchangeSymmetric M)
    (hmean : HasUnitDiagonalMean M)
    (hcore : HasUnorientedCoreWeight M q)
    (hcarrier : IsTangentialFrameResponse
      M before₀ before₁ after₀ after₁) :
    triadSurfaceArea2 after₀ after₁ =
      ((2 * q - 1) / q ^ 2) * triadSurfaceArea2 before₀ before₁ := by
  have hdetEq := unorientedClockWeight_forces_screening
    M q hexchange hmean hcore
  have hdet0 : 0 ≤ Matrix.det M := by
    rw [hdetEq]
    exact (quarticScreening_bounds q hq).1
  rw [tangentialFrameResponse_area_scale M before₀ before₁ after₀ after₁
    hcarrier hdet0]
  exact congrArg (fun x : ℝ => x * triadSurfaceArea2 before₀ before₁)
    (unorientedClockWeight_forces_quarticResponse M q
      (by linarith) hexchange hmean hcore)

/-- Surface-flux/information capstone.  Under the named tangential-carrier
hypothesis, one determinant scales positive surface area and every exterior
diagonal observable, while exterior plus hidden information is conserved. -/
theorem unorientedClock_surfaceFlux_information_capstone {n : ℕ}
    (M : Matrix (Fin 2) (Fin 2) ℝ) (q : ℝ)
    (before₀ before₁ after₀ after₁ : Fin 2 → ℝ)
    (k : Fin n → ℝ) (psi : Fin n → ℂ)
    (hq : 1 < q)
    (hexchange : IsChannelExchangeSymmetric M)
    (hmean : HasUnitDiagonalMean M)
    (hcore : HasUnorientedCoreWeight M q)
    (hcarrier : IsTangentialFrameResponse
      M before₀ before₁ after₀ after₁) :
    Matrix.det M = (2 * q - 1) / q ^ 2 ∧
      triadSurfaceArea2 after₀ after₁ =
        Matrix.det M * triadSurfaceArea2 before₀ before₁ ∧
      exteriorDataExpectation k (quarticErasureDilation q psi) =
        Matrix.det M * finiteDiagonalExpectation k psi ∧
      exteriorDataExpectation k (quarticErasureDilation q psi) +
          hiddenDataExpectation k (quarticErasureDilation q psi) =
        finiteDiagonalExpectation k psi := by
  have hinfo := unorientedClock_informationGravity_conservation
    M q k psi hq hexchange hmean hcore
  have hdet0 : 0 ≤ Matrix.det M := by
    rw [hinfo.1]
    exact (quarticScreening_bounds q hq).1
  refine ⟨unorientedClockWeight_forces_quarticResponse M q (by linarith)
      hexchange hmean hcore, ?_, hinfo.2.1, hinfo.2.2⟩
  exact tangentialFrameResponse_area_scale
    M before₀ before₁ after₀ after₁ hcarrier hdet0

/-- Isolated-horizon tandem capstone.  Two scalar curvature/triad boundary
relations transport the clock-classified curvature response to the tangential
triad frame.  The resulting area factor is the same determinant that controls
exterior information, with exact global conservation. -/
theorem isolatedHorizon_tandem_flux_information_capstone {n : ℕ}
    (M : Matrix (Fin 2) (Fin 2) ℝ) (q c : ℝ)
    (triadBefore₀ triadBefore₁ triadAfter₀ triadAfter₁ : Fin 2 → ℝ)
    (curvatureBefore₀ curvatureBefore₁
      curvatureAfter₀ curvatureAfter₁ : Fin 2 → ℝ)
    (k : Fin n → ℝ) (psi : Fin n → ℂ)
    (hq : 1 < q) (hc : c ≠ 0)
    (hexchange : IsChannelExchangeSymmetric M)
    (hmean : HasUnitDiagonalMean M)
    (hcore : HasUnorientedCoreWeight M q)
    (htransport₀ : IsScalarHorizonBoundaryTransport c M
      triadBefore₀ triadAfter₀ curvatureBefore₀ curvatureAfter₀)
    (htransport₁ : IsScalarHorizonBoundaryTransport c M
      triadBefore₁ triadAfter₁ curvatureBefore₁ curvatureAfter₁) :
    Matrix.det M = (2 * q - 1) / q ^ 2 ∧
      triadSurfaceArea2 triadAfter₀ triadAfter₁ =
        Matrix.det M * triadSurfaceArea2 triadBefore₀ triadBefore₁ ∧
      exteriorDataExpectation k (quarticErasureDilation q psi) =
        Matrix.det M * finiteDiagonalExpectation k psi ∧
      exteriorDataExpectation k (quarticErasureDilation q psi) +
          hiddenDataExpectation k (quarticErasureDilation q psi) =
        finiteDiagonalExpectation k psi := by
  have hcarrier : IsTangentialFrameResponse M
      triadBefore₀ triadBefore₁ triadAfter₀ triadAfter₁ :=
    ⟨scalarHorizonBoundary_transports_response c M
        triadBefore₀ triadAfter₀ curvatureBefore₀ curvatureAfter₀ hc htransport₀,
      scalarHorizonBoundary_transports_response c M
        triadBefore₁ triadAfter₁ curvatureBefore₁ curvatureAfter₁ hc htransport₁⟩
  exact unorientedClock_surfaceFlux_information_capstone
    M q triadBefore₀ triadBefore₁ triadAfter₀ triadAfter₁ k psi hq
      hexchange hmean hcore hcarrier

#print axioms GravityScreening.triadSurfaceFlux2_mulVec
#print axioms GravityScreening.scalarHorizonBoundary_transports_response
#print axioms GravityScreening.tangentialFrameResponse_flux_scale
#print axioms GravityScreening.tangentialFrameResponse_area_scale
#print axioms GravityScreening.unorientedClock_forces_triadFluxResponse
#print axioms GravityScreening.unorientedClock_forces_triadAreaResponse
#print axioms GravityScreening.unorientedClock_surfaceFlux_information_capstone
#print axioms GravityScreening.isolatedHorizon_tandem_flux_information_capstone

end GravityScreening
