module
public import GravityScreening.CanonicalPerronHorizonBridge
public import GravityScreening.CoreClockDuality
public import GravityScreening.HorizonCommutingSquare

@[expose] public section

/-!
# Perron optical flow and a Raychaudhuri-form identity

The canonical compressed Perron response is realized here as the endpoint of
an affine two-dimensional transverse map. Its initial velocity is symmetric
and trace free, and its acceleration vanishes. Its determinant loses a
quadratic amount; the defined expansion and shear satisfy the scalar identity
having the twist-free vacuum Raychaudhuri form.

Explicit affine null rays in flat coordinates realize this transverse map.
The displayed cuts are not generally orthogonal to their ray tangents, so
this construction does not itself establish a single null hypersurface with
these rays as generators. An orthogonal-screen construction and the physical
identification with a gravitational horizon remain separate.
-/

namespace GravityScreening

/-- Affine screen-space Jacobi map generated by a trace-free shear of
amplitude `l`. -/
noncomputable def perronOpticalJacobi
    (l t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  constitutiveBlock (t * l)

/-- Constant Jacobi velocity. It is the initial optical deformation tensor
when the initial Jacobi map is the identity. -/
noncomputable def perronOpticalVelocity
    (l : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  !![(0 : ℝ), -l; -l, 0]

/-- The Jacobi map starts at the identity. -/
theorem perronOpticalJacobi_zero (l : ℝ) :
    perronOpticalJacobi l 0 = (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [perronOpticalJacobi, constitutiveBlock]

/-- The endpoint is the constitutive response. -/
theorem perronOpticalJacobi_one (l : ℝ) :
    perronOpticalJacobi l 1 = constitutiveBlock l := by
  simp [perronOpticalJacobi]

/-- The path is exactly affine with constant velocity. -/
theorem perronOpticalJacobi_eq_identity_add
    (l t : ℝ) :
    perronOpticalJacobi l t =
      (1 : Matrix (Fin 2) (Fin 2) ℝ) +
        t • perronOpticalVelocity l := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [perronOpticalJacobi, perronOpticalVelocity, constitutiveBlock]

/-- Every Jacobi entry has the displayed constant first derivative. -/
theorem perronOpticalJacobi_entry_hasDerivAt
    (l t : ℝ) (i j : Fin 2) :
    HasDerivAt (fun s : ℝ => perronOpticalJacobi l s i j)
      (perronOpticalVelocity l i j) t := by
  have hconst :
      HasDerivAt (fun _s : ℝ => (1 : ℝ)) (0 : ℝ) t :=
    hasDerivAt_const t (1 : ℝ)
  have hraw := (hasDerivAt_id t).const_mul (-l)
  have hneg : HasDerivAt (fun s : ℝ => -(s * l)) (-l) t := by
    have hfun : (fun s : ℝ => -(s * l)) =ᶠ[nhds t]
        (fun s : ℝ => (-l) * id s) := by
      filter_upwards with x
      simp [id_eq]
      ring
    exact (hraw.congr_of_eventuallyEq hfun).congr_deriv (by ring)
  fin_cases i <;> fin_cases j <;>
    simp [perronOpticalJacobi, perronOpticalVelocity, constitutiveBlock] <;>
    first | exact hconst | exact hneg

/-- The constant Jacobi velocity has zero derivative: this is the component
form of the flat-spacetime affine Jacobi equation `J'' = 0`. -/
theorem perronOpticalVelocity_entry_hasDerivAt_zero
    (l t : ℝ) (i j : Fin 2) :
    HasDerivAt (fun _s : ℝ => perronOpticalVelocity l i j) 0 t := by
  exact hasDerivAt_const t _

/-- The initial deformation is symmetric. -/
theorem perronOpticalVelocity_symmetric (l : ℝ) :
    (perronOpticalVelocity l).transpose = perronOpticalVelocity l := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    simp [perronOpticalVelocity, Matrix.transpose_apply]

/-- Its two-dimensional trace vanishes, so the initial deformation is pure
shear with no expansion. -/
theorem perronOpticalVelocity_trace_zero (l : ℝ) :
    perronOpticalVelocity l 0 0 + perronOpticalVelocity l 1 1 = 0 := by
  simp [perronOpticalVelocity]

/-- Applying the initial shear twice produces the scalar self-response
`l^2 I`. -/
theorem perronOpticalVelocity_sq (l : ℝ) :
    perronOpticalVelocity l * perronOpticalVelocity l =
      l ^ 2 • (1 : Matrix (Fin 2) (Fin 2) ℝ) := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [perronOpticalVelocity, Matrix.mul_apply,
      Fin.sum_univ_succ] <;>
    ring

/-- Screen-area ratio along the affine Jacobi flow. -/
def perronOpticalAreaRatio (l t : ℝ) : ℝ :=
  screening (t * l)

/-- The Jacobi determinant is exactly the screen-area ratio. -/
theorem perronOpticalJacobi_det (l t : ℝ) :
    Matrix.det (perronOpticalJacobi l t) =
      perronOpticalAreaRatio l t := by
  simp [perronOpticalJacobi, perronOpticalAreaRatio,
    constitutiveBlock_det]

/-- The endpoint area loss is purely quadratic in the initial shear. -/
theorem perronOpticalAreaRatio_one (l : ℝ) :
    perronOpticalAreaRatio l 1 = 1 - l ^ 2 := by
  simp [perronOpticalAreaRatio, screening]

/-- The derivative of the screen-area ratio. -/
theorem perronOpticalAreaRatio_hasDerivAt
    (l t : ℝ) :
    HasDerivAt (perronOpticalAreaRatio l) (-2 * l ^ 2 * t) t := by
  unfold perronOpticalAreaRatio screening
  have hraw := HasDerivAt.const_sub (1 : ℝ)
    (((hasDerivAt_id t).mul_const l).pow 2)
  have hraw2 : HasDerivAt _ (-2 * l ^ 2 * t) t :=
    hraw.congr_deriv (by
      simp [id_eq]
      ring)
  simpa only [id_eq, Pi.pow_apply] using hraw2

/-- Optical expansion `theta = A'/A` for the affine screen flow. -/
noncomputable def perronOpticalExpansion (l t : ℝ) : ℝ :=
  (-2 * l ^ 2 * t) / perronOpticalAreaRatio l t

/-- Squared norm of the symmetric trace-free shear on the two-dimensional
screen. -/
noncomputable def perronOpticalShearSq (l t : ℝ) : ℝ :=
  (2 * l ^ 2) / perronOpticalAreaRatio l t ^ 2

/-- Optical deformation tensor `B = J' J⁻¹`, written without a
matrix-inverse operation. -/
noncomputable def perronOpticalDeformation
    (l t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  let A := perronOpticalAreaRatio l t
  !![(-t * l ^ 2) / A, -l / A; -l / A, (-t * l ^ 2) / A]

/-- Trace-free part of the optical deformation. -/
noncomputable def perronOpticalShear
    (l t : ℝ) : Matrix (Fin 2) (Fin 2) ℝ :=
  let A := perronOpticalAreaRatio l t
  !![(0 : ℝ), -l / A; -l / A, 0]

/-- Explicit squared Frobenius norm on a two-dimensional screen tensor. -/
def screenTensorSq
    (M : Matrix (Fin 2) (Fin 2) ℝ) : ℝ :=
  M 0 0 ^ 2 + M 0 1 ^ 2 + M 1 0 ^ 2 + M 1 1 ^ 2

/-- Squared Euclidean norm on the two-dimensional screen. -/
def screenVectorSq (x : Fin 2 → ℝ) : ℝ :=
  x 0 ^ 2 + x 1 ^ 2

/-- Transverse velocity of the ray labelled by `y`. -/
noncomputable def perronScreenVelocity
    (l : ℝ) (y : Fin 2 → ℝ) : Fin 2 → ℝ :=
  (perronOpticalVelocity l).mulVec y

/-- Minkowski norm in double-null coordinates
`ds² = -2 du dv + dx² + dy²`. -/
def doubleNullMinkowskiSq (x : Fin 4 → ℝ) : ℝ :=
  -2 * x 0 * x 1 + x 2 ^ 2 + x 3 ^ 2

/-- Constant tangent of the null ray with transverse velocity selected by the
Perron shear. -/
noncomputable def perronNullTangent
    (l : ℝ) (y : Fin 2 → ℝ) : Fin 4 → ℝ :=
  let v := perronScreenVelocity l y
  ![1, screenVectorSq v / 2, v 0, v 1]

/-- Explicit affine null ray in flat double-null coordinates. -/
noncomputable def perronNullGeodesic
    (l : ℝ) (y : Fin 2 → ℝ) (t : ℝ) : Fin 4 → ℝ :=
  let v := perronScreenVelocity l y
  ![t, t * screenVectorSq v / 2,
    y 0 + t * v 0, y 1 + t * v 1]

/-- Every ray tangent in the constructed congruence is exactly null. -/
theorem perronNullTangent_isNull
    (l : ℝ) (y : Fin 2 → ℝ) :
    doubleNullMinkowskiSq (perronNullTangent l y) = 0 := by
  simp [doubleNullMinkowskiSq, perronNullTangent, screenVectorSq]
  ring

/-- Each ray is affine: position is its initial point plus affine parameter
times its constant null tangent. -/
theorem perronNullGeodesic_affine
    (l : ℝ) (y : Fin 2 → ℝ) (t : ℝ) :
    perronNullGeodesic l y t =
      ![0, 0, y 0, y 1] + t • perronNullTangent l y := by
  funext i
  fin_cases i <;>
    (simp [perronNullGeodesic, perronNullTangent] <;> ring)

/-- The transverse cross-section of the null congruence is exactly the
Perron Jacobi map. -/
theorem perronNullGeodesic_screen_eq_Jacobi
    (l : ℝ) (y : Fin 2 → ℝ) (t : ℝ) :
    perronNullGeodesic l y t 2 =
        (perronOpticalJacobi l t).mulVec y 0 ∧
      perronNullGeodesic l y t 3 =
        (perronOpticalJacobi l t).mulVec y 1 := by
  constructor <;>
    simp [perronNullGeodesic, perronScreenVelocity,
      perronOpticalJacobi, perronOpticalVelocity, constitutiveBlock,
      Matrix.mulVec, dotProduct, Fin.sum_univ_succ] <;>
    ring

/-- The displayed deformation tensor really is the logarithmic velocity of
the Jacobi map: `B J = J'`. -/
theorem perronOpticalDeformation_mul_Jacobi
    (l t : ℝ) (harea : perronOpticalAreaRatio l t ≠ 0) :
    perronOpticalDeformation l t * perronOpticalJacobi l t =
      perronOpticalVelocity l := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [perronOpticalDeformation, perronOpticalJacobi,
      perronOpticalVelocity, constitutiveBlock, Matrix.mul_apply,
      Fin.sum_univ_succ] <;>
    field_simp [harea] <;>
    unfold perronOpticalAreaRatio screening <;>
    ring

/-- Exact expansion-plus-shear decomposition of the optical tensor. -/
theorem perronOpticalDeformation_decomposition
    (l t : ℝ) (harea : perronOpticalAreaRatio l t ≠ 0) :
    perronOpticalDeformation l t =
      (perronOpticalExpansion l t / 2) •
          (1 : Matrix (Fin 2) (Fin 2) ℝ) +
        perronOpticalShear l t := by
  ext i j
  fin_cases i <;> fin_cases j <;>
    norm_num [perronOpticalDeformation, perronOpticalExpansion,
      perronOpticalShear] <;>
    field_simp [harea]

/-- The shear part is trace free at every nonsingular cut. -/
theorem perronOpticalShear_trace_zero (l t : ℝ) :
    perronOpticalShear l t 0 0 + perronOpticalShear l t 1 1 = 0 := by
  simp [perronOpticalShear]

/-- The scalar shear norm in the Raychaudhuri law is exactly the squared
matrix norm of the trace-free optical tensor. -/
theorem screenTensorSq_perronOpticalShear
    (l t : ℝ) (harea : perronOpticalAreaRatio l t ≠ 0) :
    screenTensorSq (perronOpticalShear l t) =
      perronOpticalShearSq l t := by
  simp [screenTensorSq, perronOpticalShear, perronOpticalShearSq]
  field_simp [harea]
  ring

/-- Exact rate of change of the optical expansion. -/
noncomputable def perronOpticalExpansionRate (l t : ℝ) : ℝ :=
  (-2 * l ^ 2 * (1 + l ^ 2 * t ^ 2)) /
    perronOpticalAreaRatio l t ^ 2

/-- The displayed expansion rate is the actual derivative wherever the Jacobi
map is nonsingular. -/
theorem perronOpticalExpansion_hasDerivAt
    (l t : ℝ) (harea : perronOpticalAreaRatio l t ≠ 0) :
    HasDerivAt (perronOpticalExpansion l)
      (perronOpticalExpansionRate l t) t := by
  change HasDerivAt
    (fun s : ℝ => (-2 * l ^ 2 * s) / perronOpticalAreaRatio l s)
    (perronOpticalExpansionRate l t) t
  have hnum :
      HasDerivAt (fun s : ℝ => -2 * l ^ 2 * s) (-2 * l ^ 2) t := by
    simpa only [id_eq, mul_one] using
      (hasDerivAt_id t).const_mul (-2 * l ^ 2)
  have hden := perronOpticalAreaRatio_hasDerivAt l t
  have hquot := hnum.div hden harea
  have hquot2 : HasDerivAt _
      (perronOpticalExpansionRate l t) t :=
    hquot.congr_deriv (by
      unfold perronOpticalExpansionRate
      field_simp [harea]
      unfold perronOpticalAreaRatio screening
      ring)
  have hfun :
      (fun s : ℝ => (-2 * l ^ 2 * s) / perronOpticalAreaRatio l s) =ᶠ[nhds t]
        ((fun s : ℝ => -2 * l ^ 2 * s) / perronOpticalAreaRatio l) := by
    filter_upwards with x
    rfl
  exact hquot2.congr_of_eventuallyEq hfun

/-- Twist-free vacuum Raychaudhuri equation in two transverse dimensions.
No Ricci-focusing term is required: the finite area loss is generated by
shear self-focusing. -/
theorem perronOptical_vacuum_Raychaudhuri
    (l t : ℝ) (harea : perronOpticalAreaRatio l t ≠ 0) :
    perronOpticalExpansionRate l t =
      -(perronOpticalExpansion l t) ^ 2 / 2 -
        perronOpticalShearSq l t := by
  unfold perronOpticalExpansionRate perronOpticalExpansion
    perronOpticalShearSq
  field_simp [harea]
  ring

/-- The congruence begins with zero expansion and nonzero quadratic shear. -/
theorem perronOptical_initial_data (l : ℝ) :
    perronOpticalExpansion l 0 = 0 ∧
      perronOpticalShearSq l 0 = 2 * l ^ 2 := by
  simp [perronOpticalExpansion, perronOpticalShearSq,
    perronOpticalAreaRatio, screening]

/-- For a subunit shear, the Jacobi screen remains nonsingular throughout one
nonnegative affine step. -/
theorem perronOpticalAreaRatio_pos
    (l t : ℝ) (hl0 : 0 ≤ l) (hl1 : l < 1)
    (ht0 : 0 ≤ t) (ht1 : t ≤ 1) :
    0 < perronOpticalAreaRatio l t := by
  have htl0 : 0 ≤ t * l := mul_nonneg ht0 hl0
  have htlle : t * l ≤ l := by
    exact mul_le_of_le_one_left hl0 ht1
  have htl1 : t * l < 1 := lt_of_le_of_lt htlle hl1
  exact screening_pos ⟨by linarith, htl1⟩

/-- On the quartic root, the endpoint of the vacuum Jacobi flow is precisely
the canonical Perron-compressed horizon response. -/
theorem quarticPerronOpticalJacobi_one
    (q : ℝ) (hq4 : q ^ 4 = q + 1) (hq1 : 1 < q) :
    perronOpticalJacobi (lambda4 q) 1 =
      perronCompressedConstitutiveBlock q := by
  rw [perronOpticalJacobi_one]
  unfold perronCompressedConstitutiveBlock
  rw [quarticBiResidualCoefficient_eq_lambda4 q hq4 hq1]

/-- Its endpoint area ratio is the exact rational quartic screening factor. -/
theorem quarticPerronOpticalAreaRatio_one
    (q : ℝ) (hq1 : 1 < q) :
    perronOpticalAreaRatio (lambda4 q) 1 =
      (2 * q - 1) / q ^ 2 := by
  have hq0 : q ≠ 0 := by linarith
  rw [perronOpticalAreaRatio_one]
  exact quartic_screening_identity q hq0

/-- The observer-core self-defect is exactly the determinant of the null
Jacobi endpoint. This is the direct operator-to-geometry equality. -/
theorem quarticCoreSelfDefect_eq_perronOpticalDet
    (q mass : ℝ) (hq0 : 0 < q) (hmass : mass ≠ 0) :
    (2 * coreTraceScale (Real.log q) mass -
        coreTraceScale (2 * Real.log q) mass) / mass =
      Matrix.det (perronOpticalJacobi (lambda4 q) 1) := by
  rw [coreSelfDefect_survivor q mass hq0 hmass,
    perronOpticalJacobi_det, perronOpticalAreaRatio_one]
  rfl

/-- The one-step area loss is exactly the square of the Perron residual. -/
theorem quarticPerronOptical_area_loss
    (q : ℝ) :
    1 - perronOpticalAreaRatio (lambda4 q) 1 =
      lambda4 q ^ 2 := by
  simp [perronOpticalAreaRatio_one]

/-- The one-sided modular-energy increment required by the horizon constraint
for the optical endpoint. -/
noncomputable def perronOpticalModularEnergyIncrement
    (inverseG area l : ℝ) : ℝ :=
  inverseG * l ^ 2 * area / 4

/-- The standard horizon-cut evolution driven by that modular increment lands
exactly on the shear-focused area. -/
theorem evolvedHorizonArea_perronOptical
    (inverseG area l : ℝ) (hG : inverseG ≠ 0) :
    evolvedHorizonArea inverseG area
        (perronOpticalModularEnergyIncrement inverseG area l) =
      perronOpticalAreaRatio l 1 * area := by
  unfold evolvedHorizonArea perronOpticalModularEnergyIncrement
    perronOpticalAreaRatio screening
  field_simp [hG]

/-- The same optical update preserves the published scalar horizon constraint:
the area loss is exactly balanced by the one-sided modular-energy gain. -/
theorem horizonConstraint_perronOptical_update
    (charge K inverseG area l : ℝ)
    (hG : inverseG ≠ 0)
    (h0 : horizonConstraintResidual charge K inverseG area = 0) :
    horizonConstraintResidual charge
        (K + perronOpticalModularEnergyIncrement inverseG area l)
        inverseG (perronOpticalAreaRatio l 1 * area) = 0 := by
  rw [← evolvedHorizonArea_perronOptical inverseG area l hG]
  exact (horizonConstraintResidual_evolve charge K inverseG area
    (perronOpticalModularEnergyIncrement inverseG area l) hG).trans h0

/-- The exact vacuum Raychaudhuri law holds throughout the unit affine
interval for the positive quartic Perron root. -/
theorem quarticPerronOptical_Raychaudhuri_on_unitInterval
    (q u : ℝ) (hq1 : 1 < q) (hu0 : 0 ≤ u) (hu1 : u ≤ 1) :
    HasDerivAt (perronOpticalExpansion (lambda4 q))
        (perronOpticalExpansionRate (lambda4 q) u) u ∧
      perronOpticalExpansionRate (lambda4 q) u =
        -(perronOpticalExpansion (lambda4 q) u) ^ 2 / 2 -
          perronOpticalShearSq (lambda4 q) u := by
  obtain ⟨hl0, hl1⟩ :=
    positiveQuarticResidualWeight_mem_unitInterval q hq1
  have harea : perronOpticalAreaRatio (lambda4 q) u ≠ 0 :=
    ne_of_gt (perronOpticalAreaRatio_pos (lambda4 q) u
      (le_of_lt hl0) hl1 hu0 hu1)
  exact ⟨perronOpticalExpansion_hasDerivAt (lambda4 q) u harea,
    perronOptical_vacuum_Raychaudhuri (lambda4 q) u harea⟩

/-- Quartic optical/core capstone. The same Perron residual determines the
continuous-core phase and twice-applied trace defect, a vacuum affine Jacobi
flow with pure-shear initial data, the screen-area response, and the
one-sided modular-energy balance of the horizon constraint. -/
theorem quarticPerronOpticalCore_capstone
    (q t mass charge K inverseG area : ℝ)
    (hq4 : q ^ 4 = q + 1) (hq1 : 1 < q)
    (hmass : mass ≠ 0) (hG : inverseG ≠ 0)
    (h0 : horizonConstraintResidual charge K inverseG area = 0) :
    coreDualCharacter (Real.log q) t = quarticModularPhase q t ∧
      (2 * coreTraceScale (Real.log q) mass -
          coreTraceScale (2 * Real.log q) mass) / mass =
        screening (lambda4 q) ∧
      perronOpticalJacobi (lambda4 q) 0 =
        (1 : Matrix (Fin 2) (Fin 2) ℝ) ∧
      perronOpticalJacobi (lambda4 q) 1 =
        perronCompressedConstitutiveBlock q ∧
      perronOpticalVelocity (lambda4 q) 0 0 +
          perronOpticalVelocity (lambda4 q) 1 1 = 0 ∧
      perronOpticalVelocity (lambda4 q) *
          perronOpticalVelocity (lambda4 q) =
        lambda4 q ^ 2 • (1 : Matrix (Fin 2) (Fin 2) ℝ) ∧
      perronOpticalAreaRatio (lambda4 q) 1 =
        (2 * q - 1) / q ^ 2 ∧
      horizonConstraintResidual charge
          (K + perronOpticalModularEnergyIncrement inverseG area (lambda4 q))
          inverseG
          (perronOpticalAreaRatio (lambda4 q) 1 * area) = 0 := by
  have hq0 : 0 < q := lt_trans zero_lt_one hq1
  have hcore := quartic_core_clock_screening_pair q t mass hq0 hmass
  exact ⟨hcore.1, hcore.2,
    perronOpticalJacobi_zero (lambda4 q),
    quarticPerronOpticalJacobi_one q hq4 hq1,
    perronOpticalVelocity_trace_zero (lambda4 q),
    perronOpticalVelocity_sq (lambda4 q),
    quarticPerronOpticalAreaRatio_one q hq1,
    horizonConstraint_perronOptical_update charge K inverseG area
      (lambda4 q) hG h0⟩

/-- Full rho-Q optical gravity capstone. It joins arithmetic modular
independence, the complete bulk/local determinant, continuous-core clock
duality, affine vacuum Jacobi propagation, exact Raychaudhuri focusing, and
the horizon-cut modular-energy balance. -/
theorem rhoQOpticalRaychaudhuriGravity_capstone
    (rho q u t mass charge K inverseG area : ℝ)
    (i j : Fin 2) (screenLabel : Fin 2 → ℝ)
    (hrho3 : rho ^ 3 = rho + 1) (hrho1 : 1 < rho)
    (hq4 : q ^ 4 = q + 1) (hq1 : 1 < q)
    (hu0 : 0 ≤ u) (hu1 : u ≤ 1)
    (hmass : mass ≠ 0) (hG : inverseG ≠ 0)
    (h0 : horizonConstraintResidual charge K inverseG area = 0) :
    Irrational (Real.log rho / Real.log q) ∧
      1 / gravitationalCoupling rho q =
        (Matrix.det
            (scalarResponseMatrix gravitationalExponent (rho * q)) *
          Matrix.det (perronCompressedConstitutiveBlock q)) /
          Real.pi ^ 4 ∧
      coreDualCharacter (Real.log q) t = quarticModularPhase q t ∧
      (2 * coreTraceScale (Real.log q) mass -
          coreTraceScale (2 * Real.log q) mass) / mass =
        screening (lambda4 q) ∧
      (2 * coreTraceScale (Real.log q) mass -
          coreTraceScale (2 * Real.log q) mass) / mass =
        Matrix.det (perronOpticalJacobi (lambda4 q) 1) ∧
      doubleNullMinkowskiSq
          (perronNullTangent (lambda4 q) screenLabel) = 0 ∧
      (perronNullGeodesic (lambda4 q) screenLabel u 2 =
          (perronOpticalJacobi (lambda4 q) u).mulVec screenLabel 0 ∧
        perronNullGeodesic (lambda4 q) screenLabel u 3 =
          (perronOpticalJacobi (lambda4 q) u).mulVec screenLabel 1) ∧
      HasDerivAt
        (fun s : ℝ => perronOpticalJacobi (lambda4 q) s i j)
        (perronOpticalVelocity (lambda4 q) i j) u ∧
      HasDerivAt
        (fun _s : ℝ => perronOpticalVelocity (lambda4 q) i j) 0 u ∧
      HasDerivAt (perronOpticalExpansion (lambda4 q))
        (perronOpticalExpansionRate (lambda4 q) u) u ∧
      perronOpticalExpansionRate (lambda4 q) u =
        -(perronOpticalExpansion (lambda4 q) u) ^ 2 / 2 -
          perronOpticalShearSq (lambda4 q) u ∧
      perronOpticalJacobi (lambda4 q) 1 =
        perronCompressedConstitutiveBlock q ∧
      perronOpticalAreaRatio (lambda4 q) 1 =
        (2 * q - 1) / q ^ 2 ∧
      horizonConstraintResidual charge
          (K + perronOpticalModularEnergyIncrement inverseG area (lambda4 q))
          inverseG
          (perronOpticalAreaRatio (lambda4 q) 1 * area) = 0 := by
  have hmod := rhoQ_modularCompletion_capstone
    rho q t hrho3 hrho1 hq4 hq1
  have hrho0 : rho ≠ 0 := by linarith
  have hcore := quarticPerronOpticalCore_capstone
    q t mass charge K inverseG area hq4 hq1 hmass hG h0
  have hray := quarticPerronOptical_Raychaudhuri_on_unitInterval
    q u hq1 hu0 hu1
  exact ⟨hmod.1,
    canonicalPerron_fullGravity_determinant rho q hrho0 hq4 hq1,
    hcore.1, hcore.2.1,
    quarticCoreSelfDefect_eq_perronOpticalDet
      q mass (lt_trans zero_lt_one hq1) hmass,
    perronNullTangent_isNull (lambda4 q) screenLabel,
    perronNullGeodesic_screen_eq_Jacobi
      (lambda4 q) screenLabel u,
    perronOpticalJacobi_entry_hasDerivAt (lambda4 q) u i j,
    perronOpticalVelocity_entry_hasDerivAt_zero (lambda4 q) u i j,
    hray.1, hray.2, hcore.2.2.2.1, hcore.2.2.2.2.2.2.1,
    hcore.2.2.2.2.2.2.2⟩

#print axioms GravityScreening.perronOpticalJacobi_entry_hasDerivAt
#print axioms GravityScreening.perronOpticalVelocity_sq
#print axioms GravityScreening.perronOpticalJacobi_det
#print axioms GravityScreening.perronNullTangent_isNull
#print axioms GravityScreening.perronNullGeodesic_affine
#print axioms GravityScreening.perronNullGeodesic_screen_eq_Jacobi
#print axioms GravityScreening.perronOpticalDeformation_mul_Jacobi
#print axioms GravityScreening.perronOpticalDeformation_decomposition
#print axioms GravityScreening.screenTensorSq_perronOpticalShear
#print axioms GravityScreening.perronOpticalExpansion_hasDerivAt
#print axioms GravityScreening.perronOptical_vacuum_Raychaudhuri
#print axioms GravityScreening.quarticPerronOpticalJacobi_one
#print axioms GravityScreening.quarticCoreSelfDefect_eq_perronOpticalDet
#print axioms GravityScreening.evolvedHorizonArea_perronOptical
#print axioms GravityScreening.horizonConstraint_perronOptical_update
#print axioms GravityScreening.quarticPerronOptical_Raychaudhuri_on_unitInterval
#print axioms GravityScreening.quarticPerronOpticalCore_capstone
#print axioms GravityScreening.rhoQOpticalRaychaudhuriGravity_capstone

end GravityScreening
