module
public import GravityScreening.ModularAmplitude
public import GravityScreening.PerronTetrahedralBridge
public import Mathlib.LinearAlgebra.Matrix.Irreducible.Defs

@[expose] public section

/-!
# Perron--Frobenius data for the quartic graph KMS scale

The quartic substitution matrix is a primitive zero-one matrix.  Together
with its strictly positive eigenvector at eigenvalue `q`, this supplies the
finite-dimensional Perron--Frobenius hypotheses used by the standard KMS
theorem for the canonical gauge action on a strongly connected finite graph
algebra.  That published theorem places the unique critical KMS state at
inverse temperature `log q`.

This file proves the finite graph and exact Boltzmann-factor data.  It does
not formalize the graph C-star algebra or identify it with a gravitational
null-boundary algebra.
-/

namespace GravityScreening

/-- The quartic companion is entrywise nonnegative. -/
theorem quarticCompanion_nonnegative (i j : Fin 4) :
    0 <= quarticCompanion i j := by
  fin_cases i <;> fin_cases j <;> norm_num [quarticCompanion]

/-- Every quartic incidence entry is zero or one, as required for the
Cuntz--Krieger presentation. -/
theorem quarticCompanion_zero_or_one (i j : Fin 4) :
    quarticCompanion i j = 0 ∨ quarticCompanion i j = 1 := by
  fin_cases i <;> fin_cases j <;> norm_num [quarticCompanion]

/-- The matrix is not a permutation matrix: its second row has two distinct
outgoing incidences. -/
theorem quarticCompanion_not_permutation_witness :
    quarticCompanion 1 0 = 1 ∧ quarticCompanion 1 3 = 1 ∧
      (0 : Fin 4) ≠ 3 := by
  refine ⟨by norm_num [quarticCompanion], ?_, by decide⟩
  change (1 : ℝ) = 1
  rfl

/-- The tenth power of the quartic companion is strictly positive entrywise.
This is a concrete primitivity witness. -/
theorem quarticCompanion_pow_ten_positive (i j : Fin 4) :
    0 < (quarticCompanion ^ 10) i j := by
  fin_cases i <;> fin_cases j <;>
    norm_num [quarticCompanion, pow_succ, Matrix.mul_apply,
      Fin.sum_univ_succ]

/-- The quartic substitution matrix is primitive. -/
theorem quarticCompanion_isPrimitive :
    Matrix.IsPrimitive quarticCompanion := by
  refine ⟨quarticCompanion_nonnegative, 10, by norm_num, ?_⟩
  exact quarticCompanion_pow_ten_positive

/-- Hence the directed quartic substitution graph is strongly connected. -/
theorem quarticCompanion_isIrreducible :
    Matrix.IsIrreducible quarticCompanion :=
  quarticCompanion_isPrimitive.isIrreducible

/-- A length-four loop occurs at the distinguished quartic vertex. -/
theorem quarticCompanion_cycle_four :
    0 < (quarticCompanion ^ 4) (0 : Fin 4) 0 := by
  norm_num [quarticCompanion, pow_succ, Matrix.mul_apply,
    Fin.sum_univ_succ]

/-- A length-seven loop occurs at the same vertex. -/
theorem quarticCompanion_cycle_seven :
    0 < (quarticCompanion ^ 7) (0 : Fin 4) 0 := by
  norm_num [quarticCompanion, pow_succ, Matrix.mul_apply,
    Fin.sum_univ_succ]

/-- The displayed return lengths are coprime, giving a direct aperiodicity
certificate in addition to primitivity. -/
theorem quarticCompanion_cycleLengths_coprime : Nat.Coprime 4 7 := by
  norm_num

/-- Bezout reduction of the two loop modular frequencies.  Thus the additive
group generated by the length-four and length-seven gauge frequencies already
contains the fundamental frequency `log q`. -/
theorem quarticLoopFrequencies_generate_logQ (q : ℝ) :
    2 * (4 * Real.log q) - 7 * Real.log q = Real.log q := by
  ring

/-- Every coordinate of the quartic Perron vector is strictly positive in
the positive-root regime. -/
theorem quarticPerronVector_positive
    (q : ℝ) (hq : 0 < q) (i : Fin 4) :
    0 < quarticPerronVector q i := by
  fin_cases i <;> simp [quarticPerronVector, hq]

/-- At inverse temperature `log q`, the one-step gauge Boltzmann factor is
exactly the inverse Perron scale. -/
theorem quarticGaugeBoltzmannFactor
    (q : ℝ) (hq : 0 < q) :
    Real.exp (-Real.log q) = 1 / q := by
  rw [Real.exp_neg, Real.exp_log hq]
  simp [one_div]

/-- Consequently the response defect of one critical graph-KMS step is the
quartic residue `lambda4`. -/
theorem quarticCriticalKMS_defect
    (q : ℝ) (hq : 0 < q) :
    1 - Real.exp (-Real.log q) = lambda4 q := by
  rw [quarticGaugeBoltzmannFactor q hq]
  rfl

/-- The Connes parameter selected by the aperiodic canonical gauge-KMS
factor, expressed as a finite real invariant. -/
noncomputable def quarticConnesParameter (q : ℝ) : ℝ :=
  Real.exp (-Real.log q)

/-- The quartic Connes parameter is exactly the inverse Perron scale. -/
theorem quarticConnesParameter_eq_inv
    (q : ℝ) (hq : 0 < q) :
    quarticConnesParameter q = 1 / q := by
  exact quarticGaugeBoltzmannFactor q hq

/-- The PDT residue is one minus the discrete modular ratio parameter. -/
theorem lambda4_eq_one_sub_quarticConnesParameter
    (q : ℝ) (hq : 0 < q) :
    lambda4 q = 1 - quarticConnesParameter q := by
  rw [quarticConnesParameter_eq_inv q hq]
  rfl

/-- Exact finite-data package needed by the graph-algebra KMS theorem: the
graph is primitive, its positive vector has eigenvalue `q`, and the critical
one-step factor and defect are `1/q` and `lambda4 q`. -/
theorem quarticGraphKMS_finiteData
    (q : ℝ) (hq4 : q ^ 4 = q + 1) (hq1 : 1 < q) :
    Matrix.IsPrimitive quarticCompanion ∧
      (∀ i, 0 < quarticPerronVector q i) ∧
      quarticCompanion.mulVec (quarticPerronVector q) =
        (fun i => q * quarticPerronVector q i) ∧
      Real.exp (-Real.log q) = 1 / q ∧
      1 - Real.exp (-Real.log q) = lambda4 q := by
  have hq : 0 < q := lt_trans zero_lt_one hq1
  exact ⟨quarticCompanion_isPrimitive,
    quarticPerronVector_positive q hq,
    quarticCompanion_perron q hq4,
    quarticGaugeBoltzmannFactor q hq,
    quarticCriticalKMS_defect q hq⟩

/-- The graph-KMS defect and the quartic Perron inverse-step residual are the
same amplitude on the positive Perron line. -/
theorem quarticGraphKMS_defect_eq_perronResidual
    (q : ℝ) (hq4 : q ^ 4 = q + 1) (hq1 : 1 < q) :
    (1 - Real.exp (-Real.log q) = lambda4 q) ∧
      quarticResidual.mulVec (quarticPerronVector q) =
        (fun i => (1 - Real.exp (-Real.log q)) *
          quarticPerronVector q i) := by
  have hq : 0 < q := lt_trans zero_lt_one hq1
  have hdefect := quarticCriticalKMS_defect q hq
  refine ⟨hdefect, ?_⟩
  rw [hdefect]
  exact quarticResidual_perron q hq4 (ne_of_gt hq)

#print axioms GravityScreening.quarticCompanion_isPrimitive
#print axioms GravityScreening.quarticCompanion_isIrreducible
#print axioms GravityScreening.quarticCompanion_cycle_four
#print axioms GravityScreening.quarticCompanion_cycle_seven
#print axioms GravityScreening.quarticLoopFrequencies_generate_logQ
#print axioms GravityScreening.quarticConnesParameter_eq_inv
#print axioms GravityScreening.quarticGraphKMS_finiteData
#print axioms GravityScreening.quarticGraphKMS_defect_eq_perronResidual

end GravityScreening
